version: "3"

services:
  mongo:
    image: mongo:5.0.2 
    volumes:
      - ./data:/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: duckling
  duckling:
    platform: linux/amd64
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8000:8000
    depends_on:
      - mongo
